export const rows = [
    {
      id: 1,
      lastName: "Snow",
      firstName: "Jon",
      age: 35,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "India",
    },
    {
      id: 2,
      lastName: "Lannister",
      firstName: "Cersei",
      age: 42,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 3,
      lastName: "Lannister",
      firstName: "Jaime",
      age: 45,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 4,
      lastName: "Stark",
      firstName: "Arya",
      age: 16,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 5,
      lastName: "Targaryen",
      firstName: "Daenerys",
      age: 32,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 6,
      lastName: "Melisandre",
      firstName: "Clifford",
      age: 150,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 7,
      lastName: "Clifford",
      firstName: "Ferrara",
      age: 44,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 8,
      lastName: "Frances",
      firstName: "Rossini",
      age: 36,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 9,
      lastName: "Roxie",
      firstName: "Harvey",
      age: 65,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 10,
      lastName: "Snow",
      firstName: "Jon",
      age: 35,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 11,
      lastName: "Lannister",
      firstName: "Cersei",
      age: 42,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 12,
      lastName: "Lannister",
      firstName: "Jaime",
      age: 45,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 13,
      lastName: "Stark",
      firstName: "Arya",
      age: 16,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 14,
      lastName: "Targaryen",
      firstName: "Daenerys",
      age: 32,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 15,
      lastName: "Melisandre",
      firstName: "Clifford",
      age: 150,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 16,
      lastName: "Clifford",
      firstName: "Ferrara",
      age: 44,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 17,
      lastName: "Frances",
      firstName: "Rossini",
      age: 36,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 18,
      lastName: "Roxie",
      firstName: "Harvey",
      age: 65,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 19,
      lastName: "Snow",
      firstName: "Jon",
      age: 35,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 20,
      lastName: "Lannister",
      firstName: "Cersei",
      age: 42,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 21,
      lastName: "Lannister",
      firstName: "Jaime",
      age: 45,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 22,
      lastName: "Stark",
      firstName: "Arya",
      age: 16,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 23,
      lastName: "Targaryen",
      firstName: "Daenerys",
      age: 32,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 24,
      lastName: "Melisandre",
      firstName: "Clifford",
      age: 150,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 25,
      lastName: "Clifford",
      firstName: "Ferrara",
      age: 44,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 26,
      lastName: "Frances",
      firstName: "Rossini",
      age: 36,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
    {
      id: 27,
      lastName: "Roxie",
      firstName: "Harvey",
      age: 65,
      designation: "Full-Stack Developer",
      mobile: 9828107200,
      country: "America",
    },
  ];
  